### ISSUE TITLE
Items in transit report not including "check in service point"

### ISSUE THREAD

**Issue by jcreel** [TAMULib/mod-circulation#1]
In the code, "check in service point" are ostensibly coming in from a couple of data.  In the returned CSV, the values are blank.

**Comment by jcreel** [comment]
This fixes the download: https://github.com/TAMULib/mod-circulation/commit/d2ae516651bace6db40515debdf88fd083ffead9?diff=unified but does not address the cause of the nulls.

This work is attempting to address KACE ticket https://k1000.library.tamu.edu/userui/ticket.php?ID=53744

Get the CSV by using the "In Transit Items Report (CSV)" on the Actions download on the Inventory module.

The column is shown to work on Juniper, i.e. folio-dev.library.tamu.edu.
The column is failing on Lotus Hotfix 2, i.e. folio.library.tamu.edu.

**Comment by jeremythuff** [comment]
Can we confirm that this working in Nolana? I seem to remember that it is.

**Comment by rmathew1011** [comment]
Column `Check in service point` is populated only on Nolana but not on `PRE` and `PROD`

**Comment by jcreel** [comment]
This is considered done, as it is working in Nolana.
